### ISSUE TITLE
Error when publishing to Kafka when brokers scaled to 3

### ISSUE THREAD

**Issue by nj24** [EnMasseProject/barnabas#10]
I am trying to use the image with one change ...

Using ADVERTISED_LISTENERS and LISTENERS instead of hostname
Below are the configurations 

advertised.listeners="EXTERNAL://stb-openshift..........:30062,INTERNAL://kafka:9094"
listeners="INTERNAL://:9094,EXTERNAL://:9092"

But when scaling up the pods there is error when publishing messages 
Error as 
"WARN Error while fetching metadata with correlation id 1 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)"

Works fine with 1 zookeeper and 1 kafka node

**Comment by lghinet** [comment]
hello,
how did you solved it ?

**Comment by scholzj** [comment]
@nj24 Could you describe in a more detail what are you trying to achieve? Also, are you using the `inmemory` image or the `statefulset` images? Are you trying to have a Kafka cluster which will be using one interface for inter-broker communication and another interface for consumers / producers?

**Comment by scholzj** [comment]
Since there was no feedback for some time I will close this issue. Feel free to reopen it if you think it is still relevant. Thanks.
