### ISSUE TITLE
Create a builder image from Connect image

### ISSUE THREAD

**Issue by jpechane** [EnMasseProject/barnabas#17]
Most Connect images requires an addition of connectors that are used by the user. There are two approaches available
- mounting voulme with image jars
- create an image that derives from Connect image and add plugins to plugin dir

We propose a third way how to solve the problem. The Connect image should be able to support s2i build in form of [binary builds](https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#binary-source). The user can then just use `oc new-build --binary=true` to create the binary build from Connect image and `oc start-build` to pass the plugins into the Connect. The net result is an image stream that could be consumed by current Connect template.

The `assembly` script for this case is just coping source files into `plugins` directory.

**Comment by scholzj** [comment]
This issue should be fixed now - I will close it. 

@jpechane Feel free to reopen it if you think something is still missing or not working.
