### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by tombentley** [EnMasseProject/barnabas#21]
Currently we pull the Kafka distribution from Apache when building the image, and thus inherit the default log4j config, which logs to console and file. Since k8s/openshift will log what gets output to the console, we should fix the `log4j.properties` to not use a file logger.

**Comment by tombentley** [comment]
This is not as simple as I first thought. By default kafka will produce a number of log files, each with a daily rolling and date-based file names:

* `server.log`
* `state-change.log`
* `kafka-request.log`
* `log-cleaner.log`
* `controller.log`
* `kafka-authorizer.log`

If we just send all these log events to stdout then we will end up with a combined log that's difficult to read. We'd end up needing tooling to make the log usable.

Alternatively, keeping them as separate files is possible using a [sidecar container approach](https://kubernetes.io/docs/concepts/cluster-administration/logging/#streaming-sidecar-container). We would need to use a logging agent that deleted the old logs. If the container echoes log lines to it's stdout we can still use tools like `kubectl logs` (we would still need to logrotate those logs). Of course the container can also sent the logs somewhere else instead of, or as well as, to stdout.

Thoughts?

**Comment by scholzj** [comment]
How does the output into the console look like? Normally you would use something such as Elasticsearch to "read" the logs. Can we send everything into console and just mark the records based on the stream they belong to? Everyone will be then able to filter through exactly what he wants in the Elasticsearch.

Or was you idea with the sidecar to send the basic log to Kafka stdout and use the sidecar to feed the other files to something such as Elasticsearch?

**Comment by tombentley** [comment]
> Can we send everything into console and just mark the records based on the stream they belong to?

I didn't think so, but I guess each of the appenders could just be to the console. Let's try that...

**Comment by tombentley** [comment]
Ah, no. The problem is that to tag each line with the "logical log" it would have belonged to means I need an appender for each logical log. But if I have multiple appenders each going to stdout then I think I'll end up with duplicate log lines: a tagged one, plus the 'overall' one. We still need the overall one, because some messages won't be tagged.

**Comment by scholzj** [comment]
And do we need to tag the lines? Isn't the content or the source class etc. enough to filter the content?

**Comment by tombentley** [comment]
@scholzj yes, that would work, so long as we have/provide the tooling to post-process the unified log, elasticsearch or otherwise.

**Comment by scholzj** [comment]
That is normally something everyone does as one of the first things (at least in Kubernetes `kubectl logs` kind of sucks - for example you don't find logs for init containers, for removed pods etc.). So almost everyone installs EFK or ELK soon. I'm not sure whether there is something special on OpenShift and what is the usual practice there, but I would guess the same.

How would we do it with the sidecar? Would we actually create the sidecar with something like logstash or fluentd? Or will we just change out deployment to store the logs on a volume, take care of some log rotation and leave it to the users to add the sidecar if needed? Because every user might need something else so one sidecar fits all might be a problem.

**Comment by tombentley** [comment]
Do we need to provide the ability to view the logs from within a barnabas console? If not then we should be as unopinionated as possible about how people consume the logs.

As I understand it, log rotation in non-java programs is done by sending the process a signal which causes it to start a new log file. Thus when to roll is triggered by a `logrotate` daemon. Java doesn't provide an API for signal handling, so Java logging libraries roll the logs themselves. We should probably ensure, at a minimum, that we don't just fill up the logging volume. That means something would need to delete old logs, irrespective of how they were being consumed.

Unrelated: The ZooKeeper logs, by default, have a different layout to the Kafka ones. Should we leave that default alone, or make them consistent?

**Comment by scholzj** [comment]
I think that unopinionated means in Kubernetes / OpenShift world something like "just dump it to output".
