### ISSUE TITLE
Future of the "inmemory" setup

### ISSUE THREAD

**Issue by scholzj** [EnMasseProject/barnabas#24]
I would like to discuss the future of the `inmemory` setup. Currently there seem to be two main differences between the two setups:
* `inmemory` is using deployment instead of stateful set
* `inmemory` is using `emptyDir` as a storage instead of `PersistentVolumeClaim`

_Note: `inmemory` is actually not in memory as the name might siggest. It is still using disk but not persistent volume._

The problem from my perspective is that the `inmemory` setup is using significantly different setup from the stateful set and makes all changes more complicated. And its usability is currently anyway bad since it cannot for example scale up.

My suggestion would be to:
1. Remove the `inmemory` part completely.

or

2. Keep it, but change it to stateful set so that it is exactly the same as the stateful set deployment apart from using emptyDir as a storage. This would make it easier to maintain it and support it while adding features for the users (such as scaling up). We would also need one less image.

WDYT?

**Comment by tombentley** [comment]
I understand @ppatierno finds/has found the inmemory image useful for testing and demos and such like. However, while it may be useful for those purposes, it's not clear to me that it should be a part of enmasse/barnabas. Assuming that is indeed the case then I would suggest we remove it from this repo and let it live somewhere else.

**Comment by ppatierno** [comment]
I agree with the second approach by @scholzj

**Comment by scholzj** [comment]
@ppatierno Great, thanks. I think that would make few things easier. I will have a look at it.
