### ISSUE TITLE
Replica count should be configurable for stafulset Kafka

### ISSUE THREAD

**Issue by jpechane** [EnMasseProject/barnabas#44]
It is possible to configure the size of cluster in Connect template so it should be possible to do the same in https://github.com/EnMasseProject/barnabas/blob/master/kafka-statefulsets/resources/openshift-template.yaml for both ZooKeeper and Kafka broker

**Comment by scholzj** [comment]
Zookeeper currently works only as single node (see issue #22). For Kafka this would be possible and would make sense. In the mean time, scaling the Kafka stateful set after it was deployed could be used as a workaround.

**Comment by jpechane** [comment]
Is there any technical reasun why ZookKeeper can't run as a replicated service?

**Comment by scholzj** [comment]
It is WIP. It is slightly harder to bootstrap Zookeeper cluster because it requires to know about the other cluster members. But I'm looking into it right now.

**Comment by jpechane** [comment]
If it is about node id - when I was experimenting with it I extracted the id from `HOSTNAME` - the ordinal suffix. I passed the count of replicas into each instance so each instance genereated zoo.cfg with the list of instances.

**Comment by scholzj** [comment]
Yes, that is how it is done.
