### ISSUE TITLE
Mismatch between Connect s2i and Connect templates

### ISSUE THREAD

**Issue by jpechane** [EnMasseProject/barnabas#45]
Connect s2i is able to build a Connect image with a requested plugin(s). The resulting image is stored in an image stream. Connect template on the other hand uses Kuberentes Deployment object that is able to consume plain images, not image streams.

I propose to extend s2i template with same deployment as is in connect template but enrich it with `alpha.image.policy.openshift.io/resolve-names: '*'` - see https://trello.com/c/BW0FS66Q/845-8-integrate-imagestreams-with-non-origin-resources
The netresult will be that the deployement will be automatically started when the the build is completed.

**Comment by scholzj** [comment]
@jpechane I had a look at this and did it a bit differently. I extended the S2I deployment to also contain a DeploymentConfig which is bound directly to the ImageStream. If you want to give it a try, you can have a look at the PR #63. The updated S2I Docker image is available as scholzj/kafka-connect-s2i:latest. It would be great to hear from you whether what I did works fine for you.
