### ISSUE TITLE
Different images for Zookeeper and Kafka

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/barnabas#5]
Think about having two different images for Zookeeper and Kafka removing the command to start from the YAML file and putting it into Dockerfile.

**Comment by goern** [comment]
good idea, and we should think about making zookeeper a ensemble... see https://zookeeper.apache.org/doc/r3.3.2/zookeeperAdmin.html#sc_zkMulitServerSetup

**Comment by scholzj** [comment]
@ppatierno Would you just separate the scripts for starting Zookeeper / Kafka? Or would you move to completely separate images - i.e. the Zookeeper image using standalone Zookeeper distribution instead of using the Zookeeper bundled with Kafka?

**Comment by ppatierno** [comment]
@scholzj I think that we should have different images and using standalone Zookeeper distribution instead of the one bundled with Kafka. Wdyt ?

**Comment by scholzj** [comment]
FYI: I raised a separate issue #22 to make the Zookeeper run as multi node ensemble. This issue will be used to separate the images.

**Comment by scholzj** [comment]
Separation of Docker images for Kafka and Zookeeper has been addressed by PR #20. The same PR also removed the commands. 

Since Zookeeper ensemble is covered by #22, I think this issue can be closed.
