### ISSUE TITLE
Is it okay to make sure it's all right?

### ISSUE THREAD

**Issue by leenux** [EnMasseProject/barnabas#73]
`kafka-statefulsets/resources/zookeeper.yaml`
```
            - name: clientport
              containerPort: 2181
              protocol: TCP
            - containerPort: 2888
              name: clustering
              protocol: TCP
            - containerPort: 3888
              name: leaderelection
              protocol: TCP

```
The 1st line is `- name: clientport` and 2nd line is `containerPort: 2181`

The 4th line is  `- containerPort: 2888` and 5th line is `name: clustering`

The 7th line is `- containerPort: 3888` and 8th line is `name: leaderelection`

**Comment by scholzj** [comment]
@leenux I'm not sure I understand what the problem is ... is it the different order of the fields for each port?
