### ISSUE TITLE
Schema support is disabled in Connect

### ISSUE THREAD

**Issue by jpechane** [EnMasseProject/barnabas#75]
Connect image by default disables schema support - https://github.com/EnMasseProject/barnabas/blob/d281eb9c2ec89d0db999ea77cd2298b707cc14d6/kafka-connect/scripts/kafka_connect_run.sh#L52-L53

It should be possible to override the setting. Also it is probably better solution to have schemas enabled by default.

**Comment by scholzj** [comment]
@jpechane Two questions ...

1) I don't remeber it exactly and would need to try it out. But I believe that when I simply set it to true it will require also some other parameters to be specified. Can I really just set this to true and not change anything else?
2) What about `internal.key.converter.schemas.enable` and `internal.value.converter.schemas.enable`?

**Comment by jpechane** [comment]
1. It should just work. Only when Avro serializers are used then schema registry has to be provided.
2. The are almost never changed so you can keep them as is.

**Comment by scholzj** [comment]
@jpechane Yeah, it seems you are right. It probably matters only once some connector is deployed.

**Comment by gunnarmorling** [comment]
Sweet, thanks for the quick fix, @scholzj!
