### ISSUE TITLE
Cleanup images on Docker Hub?

### ISSUE THREAD

**Issue by scholzj** [EnMasseProject/barnabas#78]
We have currently serveral Docker images on Docker Hub which are not used anymore and not updated anymore:
* [kafka-inmemory](https://hub.docker.com/r/enmasseproject/kafka-inmemory/)
* [kafka-persistent](https://hub.docker.com/r/enmasseproject/kafka-persisted/)

We should think what to do with them (e.g. delete them from Docker Hub?).

**Comment by tombentley** [comment]
Do we know if anyone is using them?

Presumably an alternative would be to provide a description to say they're unsupported, deprecated and point to the current images. That way we're at least not spoiling anyone's day.

**Comment by ppatierno** [comment]
I'm pretty sure that no-one is using the kafka-persisted. I don't know about the kafka-inmemory. I think that all main people who know about "barnabas" project are using the kafka-statefulsets.

**Comment by scholzj** [comment]
@tombentley They have quite a lot of pulls - lot more than kafka-statfulsets image. But it is hard to say whether this number is still raising.

An alternative which comes to my mind is to push the kafka-statefulsets image also under these two other names. But that seems to just shift the problem into the future and not really solve it.

**Comment by ppatierno** [comment]
@scholzj I think that people should expect these problems when a platform/framework/project isn't released yet. I think we can just delete them and if someone will complain about that we can explain that.

**Comment by tombentley** [comment]
I've updated the long and short descriptions of the images on Dockerhub, with a proposed deletion date of 2018/12/31, and setup a reminder to delete those image on that date.
