### ISSUE TITLE
kafka_run.sh script not found error

### ISSUE THREAD

**Issue by kunallimaye** [EnMasseProject/barnabas#8]
`kafka-statefulsets/resources/openshift-template.yaml` on line 109 references a script `/opt/kafka_2.11-${KAFKA_VERSION}/kafka_run.sh` that doesn't exist.

The script should be updated to `/opt/kafka/kafka_run.sh`

**Comment by ppatierno** [comment]
Closed with #9

**Comment by goern** [comment]
This issue could be closed :)
